name: Release Container Registy

on:
  workflow_call:
    secrets:
      api-pat:
        required: true
    inputs:
      work-dir: 
        required: true
        type: string
      platform: 
        required: true
        type: string

jobs:
  push-to-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.api-pat }}


      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ${{ inputs.work-dir }}/Dockerfile
          platforms: ${{ inputs.platform }}
          tags: |
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ github.run_id }}
            
